### ISSUE TITLE
not compatible with Advanced Company, the masked will remain the original masked, and cosmetics won't show

### ISSUE THREAD

**Issue by drink1101** [HomelessGinger/MaskedEnemyOverhaul#10]
Advanced company enabled
![image](https://github.com/HomelessGinger/MaskedEnemyOverhaul/assets/85337928/e4da114c-9f4d-42a2-88c7-09290a877c90)
![image](https://github.com/HomelessGinger/MaskedEnemyOverhaul/assets/85337928/e276b02c-394c-40ad-b39f-525e06fcbcab)

diasbled
![image](https://github.com/HomelessGinger/MaskedEnemyOverhaul/assets/85337928/1e192638-0b18-44b1-a3ee-31f3b0be0bb6)
![image](https://github.com/HomelessGinger/MaskedEnemyOverhaul/assets/85337928/0bc4c74f-88fc-45b5-92fb-3bbe636546d8)

**Comment by IanBarthel** [comment]
fixed this a few days ago
