### ISSUE TITLE
masked can pass through ship door

### ISSUE THREAD

**Issue by bahaha07** [HomelessGinger/MaskedEnemyOverhaul#12]
Idk why but masked enemies can pass through ship door. I think it has something to do with pathfinding software.
And can you add remove player's name tag (for player no masked) option too. Such a feature would be very nice

**Comment by IanBarthel** [comment]
there is already a mod that removes names, so i will not be doing it myself. and them passing through the door is a vanilla bug, has nothing to do with my code and will not be fixed by me
