### ISSUE TITLE
Assigning random players to mimic conflicts with Mirage

### ISSUE THREAD

**Issue by qwbarch** [HomelessGinger/MaskedEnemyOverhaul#18]
Mirage: https://thunderstore.io/c/lethal-company/p/qwbarch/Mirage/

Can this feature become optional/configurable? It conflicts with mirage and causes a mismatch between a mimicked voice and the shown suit

Specifically this chunk of code (and anywhere else that might change what the masked enemy is mimicking) is the conflict:
https://github.com/HomelessGinger/MaskedEnemyOverhaul/blob/513454f187a4b074a89e70b19f5459cb4c957331/Patches/MaskedVisualRework.cs#L62-L67

**Comment by qwbarch** [comment]
Since it seems like HomelessGinger is not actively maintaining MEO, pinging @Capital-Asterisk. If you could add that to your fork for now, that'd be great!

**Comment by Capital-Asterisk** [comment]
Are you implying an option to just not touch the mimickingPlayer member?

**Comment by qwbarch** [comment]
> Are you implying an option to just not touch the mimickingPlayer member?

Yes, exactly that. That way users who use Mirage can still use MEO without any conflicts

**Comment by qwbarch** [comment]
I see it's been added, thanks!
