### ISSUE TITLE
Add the ability to carry objects infected with masks

### ISSUE THREAD

**Issue by Paradox75831004** [HomelessGinger/MaskedEnemyOverhaul#5]
Make it as confusing as possible - whether this is a real player or not - so that they can somehow pick up items from a corpse themselves, or, like beetles, find items and just carry them. Scary? Unclear. Who is who?!?!?

**Comment by IanBarthel** [comment]
im debating this, i want to keep my mod as visual as possible, where i barely touch (if at all) the ai of the monster. this is to keep it as compatible as possible. I highly recommend looking at the MaskedAIRevamp mod, it is in beta but mods like that are why i did not touch the AI, so people can mod the AI to be however they want while using my mod.
