### ISSUE TITLE
Possibility to support ModelReplacementAPI mods?

### ISSUE THREAD

**Issue by htkg** [HomelessGinger/MaskedEnemyOverhaul#6]
Thank you for your mod!

Is there possibility to add support for suits that being changed by ModelReplacementAPI like Hololive_Company mod by Tacocat12?

**Comment by IanBarthel** [comment]
possibly. i have not looked into it myself, and ive been told by a couple people that it is next to impossible to make it work every time but i am not sure if thats true. ill look into it one day
