### ISSUE TITLE
Potential Mistake and a Config Request

### ISSUE THREAD

**Issue by kking117** [HomelessGinger/MaskedEnemyOverhaul#7]
I looked at the source tab on the Thunderstore and noticed that "MidOutsideEnemySpawnCurve" is using "MaxSpawnCountConfig.Value" is this intended?

Also is it possible to set the maximum number of masked for specifically zombie apocalypse mode? I know "Max Number of Masked" works but I'd like to keep the amount lower when it isn't happening.

**Comment by IanBarthel** [comment]
uh it definitely is not haha. thanks for bringing that up. and yeah, ill make a config for that
